---
title: "Stanford"
author: Sherlyn Jemimah, PhD
output: html_notebook
---


```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(Cairo)
library(ggrepel)
```

```{r}
gc.n1_5846 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5846_n1/")
dn1 <- CreateSeuratObject(counts = gc.n1_5846, project = "1-N", min.cells = 3, min.features = 200)

gc.t1_5846 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5846_t1/")
dt1 <- CreateSeuratObject(counts = gc.n1_5846, project = "1-T", min.cells = 3, min.features = 200)

gc.n1_5866 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5866_n1/")
dn2 <- CreateSeuratObject(counts = gc.n1_5846, project = "2-N", min.cells = 3, min.features = 200)

gc.t1_5866 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5866_t1/")
dt2 <- CreateSeuratObject(counts = gc.n1_5846, project = "2-T", min.cells = 3, min.features = 200)

# gc.n2_5866 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5866_n2/")
# dn2_ <- CreateSeuratObject(counts = gc.n1_5846, project = "N", min.cells = 3, min.features = 200)
# 
# gc.t2_5866 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5866_t2/")
# dt2_ <- CreateSeuratObject(counts = gc.n1_5846, project = "T", min.cells = 3, min.features = 200)

gc.n1_5931 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5931_n1/")
dn3 <- CreateSeuratObject(counts = gc.n1_5846, project = "3-N", min.cells = 3, min.features = 200)

gc.t1_5931 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5931_t1/")
dt3 <- CreateSeuratObject(counts = gc.n1_5846, project = "3-T", min.cells = 3, min.features = 200)

# gc.n2_5931 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5931_n2/")
# dn3_ <- CreateSeuratObject(counts = gc.n1_5846, project = "N", min.cells = 3, min.features = 200)
# 
# gc.t2_5931 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/5931_t2/")
# dt3_ <- CreateSeuratObject(counts = gc.n1_5846, project = "T", min.cells = 3, min.features = 200)

gc.n1_6207 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6207_n1/")
dn4 <- CreateSeuratObject(counts = gc.n1_5846, project = "4-N", min.cells = 3, min.features = 200)

gc.t1_6207 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6207_t1/")
dt4 <- CreateSeuratObject(counts = gc.n1_5846, project = "4-T", min.cells = 3, min.features = 200)

gc.n1_6342 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6342_n1/")
dn5 <- CreateSeuratObject(counts = gc.n1_5846, project = "5-N", min.cells = 3, min.features = 200)

gc.t1_6342 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6342_t1/")
dt5 <- CreateSeuratObject(counts = gc.n1_5846, project = "5-T", min.cells = 3, min.features = 200)

gc.n1_6592 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6592_n1/")
dn6 <- CreateSeuratObject(counts = gc.n1_5846, project = "6-N", min.cells = 3, min.features = 200)

gc.t1_6592 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6592_t1/")
dt6 <- CreateSeuratObject(counts = gc.n1_5846, project = "6-T", min.cells = 3, min.features = 200)

gc.n1_6649 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6649_n1/")
dn7 <- CreateSeuratObject(counts = gc.n1_5846, project = "7-N", min.cells = 3, min.features = 200)

gc.t1_6649 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6649_t1/")
dt7 <- CreateSeuratObject(counts = gc.n1_5846, project = "7-M", min.cells = 3, min.features = 200)

gc.n1_6709 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6709_n1/")
dn8 <- CreateSeuratObject(counts = gc.n1_5846, project = "8-N", min.cells = 3, min.features = 200)

gc.t1_6709 <- Read10X(data.dir="D:/scRNASeq/GC/Stanford/6709_t1/")
dt8 <- CreateSeuratObject(counts = gc.n1_5846, project = "8-T", min.cells = 3, min.features = 200)
```

```{r}
# "TCAGCTCAGGCACATG"
dt8@meta.data[grepl("TCAGCTC", rownames(dt8@meta.data)),]
```


# read in cell identities
```{r}
df <- read.delim("D:/scRNASeq/GC/Stanford/cell_labels.csv", sep=",")
df

barcodes <- c()
for (i in df$cell_barcode){
  barcodes <- c(barcodes, paste0(strsplit(i,split="-")[[1]][1], "_", df[df$cell_barcode==i,"orig.ident"]) )
}

df$cell_barcode <- barcodes
df
```

```{r}
md <- merge(dn1, c(dn2, dn3, dn4, dn5, dn6, dn7, dn8, dt1, dt2, dt3, dt4, dt5, dt6, dt7, dt8), project = "Stanford", merge.data = TRUE)
```
```{r}
mnorm <- merge(dn1, c(dn2, dn3, dn4, dn5, dn6, dn7, dn8), project = "Stanford", merge.data = TRUE)
mtum <- merge(dt1, c( dt2, dt3, dt4, dt5, dt6, dt7, dt8), project = "Stanford", merge.data = TRUE)
#FeaturePlot(mnorm,features = c("C6", "C7"))
```



```{r}
VlnPlot(md,features = c("C6", "C7"))
```


```{r}
length(md@meta.data$orig.ident)
md@meta.data
unique(md@meta.data$orig.ident)
```

```{r}
# "TCAGCTCAGGCACATG"
md@meta.data[grepl("TCAGCTCAGG",rownames(md@meta.data)), ]
```


```{r}
barcodes <- c()
for (i in rownames(md@meta.data)){
  barcodes <- c(barcodes, paste0(strsplit(i, "_", perl=TRUE)[[1]][1], "_", md@meta.data[i,"orig.ident"]))
}

rownames(md@meta.data) = barcodes
# md@meta.data <- md@meta.data %>% 
#   rownames_to_column(var="cell_barcode")
```

```{r}
md@meta.data
```

```{r}
df <- read.delim("D:/scRNASeq/GC/Stanford/cell_labels.csv", sep=",") %>% 
  mutate(cell_barcode = paste0(cell_barcode,"_",orig.ident))
df 
```

```{r}
GetCellType <- function(id){
  if (length(df[df$cell_barcode==id,"final_celltype"])==1){
    return (df[df$cell_barcode==id,"final_celltype"][[1]])
  }else{
    if (strsplit(id,"")[[1]][nchar(id)-1]=="n"){
      return ("Normal")
    }
    else{
      return ("Tumor")
    }
  }
}
```

```{r}
md@meta.data[rownames(md@meta.data) %in% df$cell_barcode,]
```

```{r}
md@meta.data["CellType"] <- apply(md@meta.data,1,GetCellType)
```

```{r}
write.table( md@meta.data, "C:/Users/csislyn/Desktop/check.txt", sep="\t", quote=F)
```



```{r}
md@meta.data <- md@meta.data %>% 
  left_join(df, by="cell_barcode")
md@meta.data
```

```{r}
View(drop_na(md@meta.data))
```



# Quality check and filtering
```{r}
# Visualize QC metrics as a violin plot
d_norm[["percent.mt"]] <- PercentageFeatureSet(d_norm, pattern = "^MT-")
d_tum[["percent.mt"]] <- PercentageFeatureSet(d_tum, pattern = "^MT-")
VlnPlot(d_norm, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
VlnPlot(d_tum , features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
# filter
d_norm <- subset(d_norm, subset = nFeature_RNA > 200 & percent.mt < 5)
d_tum <- subset(d_tum, subset = nFeature_RNA > 200 & percent.mt < 5)
VlnPlot(d_norm, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
VlnPlot(d_tum , features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
plot1 <- VlnPlot(d_norm, features = c("RAD51","C6","C7"))
plot1

plot2 <- VlnPlot(d_tum , features = c("RAD51","C6","C7"))
plot2

# RAD51 missing in Standford data.
```

```{r}
#merge and log-norm data
mer_dlog <- merge(d_norm, d_tum)
mer_dlog <- NormalizeData(mer_dlog)
```

```{r}
md <- FindVariableFeatures(md, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top20 <- head(VariableFeatures(md), 20)

# plot variable features with and without labels
plot3 <- VariableFeaturePlot(md)
plot4 <- LabelPoints(plot = plot3, points = top20, repel = TRUE)
plot4

# write.table( HVFInfo(mer_dlog), file = "D:/scRNASeq/GC/Stanford/varfeatures.csv", sep=",", quote=F )
```

```{r}
df <- read.delim("D:/scRNASeq/GC/Stanford/cell_labels.csv", sep=",")

barcodes <- c()
for (i in df$cell_barcode){
  barcodes <- c(barcodes, strsplit(i,split="-")[[1]][1])
}

df$cell_barcode <- barcodes
```

```{r}


barcodes <- c()
for (i in rownames(d_tum@meta.data)){
  x <- strsplit(i, "_(?!.*_)", perl=TRUE)[[1]][2]
  barcodes <- c(barcodes,strsplit(x, "-", perl=TRUE)[[1]][1])
}

d_tum@meta.data <- d_tum@meta.data %>% 
  mutate(cell_barcode = barcodes) %>% 
  left_join(y=df, by=c("cell_barcode") )

d_norm@meta.data
d_tum@meta.data
```


```{r}
d_norm.list <- SplitObject(d_norm, split.by = "orig.ident")
```

```{r}
library(ggplot2)
library(cowplot)

md <- ScaleData(md)
md <- RunPCA(md, npcs=30, verbose = F)
md <- RunUMAP(md, reduction = "pca", dims = 1:30 )
Idents(md) <- md@meta.data$CellType

```
```{r}
VlnPlot(md, features = c("C6", "C7", "RAD51", "RAD51C", "RAD51B", "RAD51D", "RAD51AP1"))

```


```{r}
#md <- RunUMAP(md, dims = 1:8)
library(RColorBrewer)
pl <- DimPlot(md, reduction = "umap",group.by = "orig.ident", label=TRUE)

library(Cairo)
CairoPNG(file="C:/Users/csislyn/Desktop/UMAP.png",
      units="in", 
      width=10, 
      height=7,
      pointsize=8, 
      dpi=300)
print(pl)
dev.off()
```

```{r}
data <- GetAssayData(object = md, assay = "RNA", slot = "data")[c("C6","C7"),]
data
```

```{r}
mnorm[["C6"]] <- PercentageFeatureSet(mnorm, pattern = "C6")
mnorm[["C7"]] <- PercentageFeatureSet(mnorm, pattern = "C7")
VlnPlot(mnorm, features=c("C6","C7"), pt.size=0, slot = "counts", fill.by = mnorm@meta.data$nCount_RNA) +
  geom_boxplot(width=0.1,fill="white", notch = T) + 
  scale_color_grey()

mtum[["C6"]] <- PercentageFeatureSet(mtum, pattern = "C6")
mtum[["C7"]] <- PercentageFeatureSet(mtum, pattern = "C7")
VlnPlot(mtum, features=c("C6","C7"), pt.size=0, slot = "counts", fill.by = mtum@meta.data$nCount_RNA) +
  geom_boxplot(width=0.1,fill="white", notch = T) + 
  scale_color_grey()
```

```{r}
#mnorm <- ScaleData(mnorm)
#md <- ScaleData(md)
# , levels = c("5846_n1","5866_n1","5866_n2", "5931_n1", "5931_n2", "6207_n1", "6342_n1", "6592_n1", "6649_n1", "6709_n1", "5846_t1","5866_t1","5866_t2", "5931_t1", "5931_t2", "6207_t1", "6342_t1", "6592_t1", "6649_t1", "6709_t1")
#md@active.ident <- factor(x = md@active.ident)
png("C:/Users/csislyn/Desktop/hmap.png", units = "in", res=1200, width = 18, height = 3.6)
DoHeatmap(md, features = c("C6", "C7"), angle = 90, size=9) + 
  theme(legend.position = 'none') +
  theme(axis.text.y = element_text(size = 28), text = element_text(size = 12)) +
  scale_fill_gradientn(colors = c("white","navy blue"))
dev.off()
```
```{r}
assay_data <- GetAssayData(object = md, assay = "RNA", slot = "scale.data")[c("C6", "C7", "C1QA", "C1QB", "C1QC", "C1R", "C1S", "C2", "C3", "C3AR1", "C4BPB", "C5",  "C5AR1", "C5AR2"),]
write.table(assay_data, "C:/Users/csislyn/Desktop/Stanford_complement_data.csv", quote=F, sep=",")
```

```{r}
write.table(md@meta.data, "C:/Users/csislyn/Desktop/Stanford_complement_data_cellmeta.csv", quote=F, sep=",")
```

```{r}
# md <- ScaleData(md)
md <- FindVariableFeatures(md,selection.method = "vst", nfeatures = 2000)
reference.list <- list(dn1, dn2, dn3, dn4, dn5, dn6, dn7, dn8, dt1, dt2, dt3, dt4, dt5, dt6,dt7,dt8)
md.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
md.integrated <- IntegrateData(anchorset = md.anchors, dims = 1:30)
md.integrated <- ScaleData(md.integrated, verbose = FALSE)
md.integrated <- RunPCA(md.integrated, npcs = 30)
```

```{r}
md.integrated <- RunTSNE(object = md.integrated, dims.use = 1:30, do.fast = TRUE)
md.integrated <- FindNeighbors(md.integrated, reduction = "pca", dims = 1:30)


# Examine and visualize PCA results a few different ways
#print(md[["pca"]], dims = 1:5, nfeatures = 5)

```

```{r}
#md <- RunUMAP(md, dims = 1:2)
md.integrated <- FindClusters(md.integrated, resolution = 0.05)
plot4 <- DimPlot(md.integrated, reduction = "tsne",label=TRUE) +
  theme(legend.position = 'none')

# library(Cairo)
# CairoPNG(file="D:/scRNASeq/GC/Stanford/tsne_.png",
#       units="in", 
#       width=10, 
#       height=7,
#       pointsize=8, 
#       dpi=600)
# print(plot4)
# dev.off()

plot4
```

```{r}
# md <- ScaleData(md)

# integrate normal data
reference.list <- list(dn1, dn2, dn3, dn4, dn5, dn6, dn7, dn8)
md.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)

reference.list <- list(dt1, dt2, dt3, dt4, dt5, dt6, dt7, dt8)
md.tumors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)

md.tumors <- IntegrateData(anchorset = md.tumors, dims = 1:30)
md.tumors <- IntegrateData(anchorset = md.anchors, dims = 1:30)
```

```{r}
md.tumors <- ScaleData(md.tumors, verbose = FALSE)
md.tumors <- RunPCA(md.tumors, npcs = 30)

```
```{r}
GetCellType <- function(id){
  if (length(df[df$cell_barcode==id,"final_celltype"])==1){
    return (df[df$cell_barcode==id,"final_celltype"][[1]])
  }else{
    if (strsplit(id,"")[[1]][nchar(id)-1]=="n"){
      return ("Normal")
    }
    else{
      return ("Tumor")
    }
  }
}

md@meta.data[rownames(md@meta.data) %in% df$cell_barcode,]
```



```{r}
#md <- RunUMAP(md, dims = 1:2)

md.tumors <- FindNeighbors(md.tumors, reduction = "pca", dims = 1:30)
md.tumors <- FindClusters(md.tumors, resolution = 0.05)
md.tumors <- RunTSNE(object = md.tumors, dims.use = 1:30, do.fast = TRUE)
p4 <- DimPlot(md.tumors, reduction = "tsne",label=TRUE) +
  theme(legend.position = 'none')

library(Cairo)
CairoPNG(file="D:/scRNASeq/GC/Stanford/tsne_.png",
      units="in", 
      width=10, 
      height=7,
      pointsize=8, 
      dpi=600)
print(plot4)
dev.off()
```

