---
title: "Effect of extended treatment with HU and GSK591 on IFN-alpha pathway in MCF10a cells"
author: Sherlyn Jemimah, PhD
output: html_notebook
---


```{r}
## load libraries
library(DEGreport)
library(DESeq2)
library(ggplot2)
library(ggrepel)
library(pheatmap)
library(RColorBrewer)
library(tidyverse)

library(org.Hs.eg.db)
library(DOSE)
library(pathview)
library(clusterProfiler)
library(AnnotationHub)
library(ensembldb)
library(tidyverse)
library(annotables)

library(Cairo)
```

```{r}
#  files
count_file <- "D:/Clarissa/HU-GSK591-extended/2646_merged_gene_counts.txt"
smple_info <- "D:/Clarissa/HU-GSK591-extended/meta.txt"

## sample information/metadata
coldata <- read.table(smple_info,header=TRUE,sep="\t",row.names=1)
## count data
cts <- read.table(count_file,header=TRUE,sep="\t", row.names="Gene" )
```

```{r}
## Check that sample names match in both files
all(colnames(cts) %in% rownames(coldata))
all(colnames(cts) == rownames(coldata))
```
```{r}
## DESeq
dds <- DESeqDataSetFromMatrix(countData=cts, colData=coldata, design = ~ Treatment)
dds <- estimateSizeFactors(dds)
# Normalize counts
normalized_counts <- counts(dds, normalized=TRUE)
# save normalized data
write.table(normalized_counts, file="D:/Clarissa/HU-GSK591-extended/normdata.txt", sep="\t", quote=F, col.names=NA)
```

```{r}
# Transform counts for data visualization
rld <- varianceStabilizingTransformation(dds, blind=TRUE)

## PCA plot
plot <- plotPCA(rld, intgroup="Treatment")
CairoPNG(file="D:/Clarissa/HU-GSK591-extended/PCA-plot.png",
      units="in", 
      width=5, 
      height=4, 
      pointsize=12, 
      dpi=300)
print(plot)
dev.off()
```

```{r}
## Run analysis
dds <- DESeq(dds)
## Define contrasts, extract results table, and shrink the log2 fold changes
contrast_var <- c("Treatment", "HU", "DMSO")
dds <- nbinomWaldTest(dds)
resultsNames(dds)

res     <- results(dds, contrast=contrast_var, alpha = 0.05)#, cooksCutoff=FALSE)
reshrnk <- lfcShrink(dds,res=res,type="ashr")
```

```{r}
# Set thresholds
padj.cutoff <- 0.05
lfc.cutoff <- 1.5
# Tibble the results table
reshrnk_tb <- reshrnk %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()
# subset to keep significant genes
sig <- reshrnk_tb %>%
        dplyr::filter(padj < padj.cutoff & abs(log2FoldChange) > lfc.cutoff)
```
 
```{r}
### Extract normalized expression for significant genes from the Z-treated and control samples, and set the gene column (1) to row names

immgenes <- as.vector(scan("D:/CRP-Proposal_Feb2021/nano_imgenes_all.txt",what=character(),sep="\n"))

# top20 <- reshrnk_tb %>%
#   na.omit() %>%
#   dplyr::filter(baseMean < 2) %>%
#   arrange(log2FoldChange) %>% 	#Arrange rows by log2FoldChange
#   pull(gene) %>% 		#Extract character vector of ordered genes
#   head(n=30) 		#Extract the first 20 genes
# 
# bot20 <- reshrnk_tb %>%
#   na.omit() %>%
#   dplyr::filter(baseMean < 2) %>%
#   arrange(log2FoldChange) %>% 	#Arrange rows by log2FoldChange
#   pull(gene) %>% 		#Extract character vector of ordered genes
#   tail(n=30) 		#Extract the first 20 genes

sig_imm <- c(intersect(immgenes, c(sig$gene)))

# x <- which(rownames(normalized_counts) %in% sig_imm)
# norm_edit <- as.tibble(normalized_counts) %>%
#   dplyr::filter(row.names(normalized_counts) %in% immgenes)

sig_table <- sig %>%
  dplyr::filter(sig$gene %in% sig_imm)
write.table(sig_table, "D:/Clarissa/HU-GSK591-extended/sig_DEGsimmune_HUvsDMSO.txt", sep="\t", row.names = F, quote=F)
norm_sig <- normalized_counts[c(sig_table$gene), c("MCF10a_DMSO_1", "MCF10a_DMSO_2", "MCF10a_HU_1", "MCF10a_HU_2")]

# norm_sig <- normalized_counts[c("IFIT3", "IFI27", "IFI6", "IFIT1", "IFIT2", "ISG15", "OAS3", "IRF7", "OAS2", "SOCS1", "SAMHD1", "OAS1", "ISG20", "IRF1", "OASL", "HLA-F", "IP6K2", "STAT1", "IRF5", "IFNAR1", "IFI35", "STAT2", "IFNAR2"), c("MCF10a_DMSO_1", "MCF10a_DMSO_2", "MCF10a_HU_1", "MCF10a_HU_2")]

# ### Annotate our heatmap (optional)
# annotation <- coldata %>% 
# 	dplyr::select(samplename, Treatment) %>% 
# 	data.frame(row.names = "samplename")

### Set a color palette
heat_colors <- brewer.pal(9, "YlGnBu")

### Run pheatmap
hmap<- pheatmap(norm_sig,
                show_rownames = T,
                cluster_rows = F,
                cluster_cols = F,
                fontsize = 10, 
                scale = "row", 
                fontsize_row = 10, 
                height = 20)

CairoPNG(file="D:/Clarissa/HU-GSK591-extended/sig_DEGsimmune_HUvsDMSO.png",
      units="in", 
      width=3.6, 
      height=18,
      pointsize=8, 
      dpi=300)
print(hmap)
dev.off()

```

```{r}
require(ggplot2)
library(grid)
library(cowplot)
library(scales)

ntop <- 30
ggdata <- read.csv("D:/Clarissa/HU-GSK591-extended/Combo_vs_HU_hallmark.csv",header = T)
ggdata$Pathway <- factor(ggdata$Pathway, levels=ggdata$Pathway) # prevent ggplot from changing the order of the pathways
gg1 <- ggplot(ggdata,
              aes(x = Pathway, y = NES, size = Size, fill = Pval)) +

  expand_limits(y = 1) +
  geom_point(shape = 21) +
  scale_size(range = c(2.5,12.5)) +
  scale_fill_continuous(low = 'royalblue', high = 'red4') +

  ggplot2::coord_flip() +

  xlab('') + ylab('Enrichment score') +
  labs(title = 'Combo v. HU') +


  theme_bw(base_size = 24) +
  theme(
    legend.position = 'right',
    legend.background = element_rect(),
    plot.title = element_text(angle = 0, size = 16, face = 'bold', vjust = 1),
    plot.subtitle = element_text(angle = 0, size = 14, face = 'bold', vjust = 1),
    plot.caption = element_text(angle = 0, size = 12, face = 'bold', vjust = 1),

    axis.text.x = element_text(angle = 0, size = 12, face = 'bold', hjust = 1.10),
    axis.text.y = element_text(angle = 0, size = 12, face = 'bold', vjust = 0.5),
    axis.title = element_text(size = 12, face = 'bold'),
    axis.title.x = element_text(size = 12, face = 'bold'),
    axis.title.y = element_text(size = 12, face = 'bold'),
    axis.line = element_line(colour = 'black'),

    #Legend
    legend.key = element_blank(), # removes the border
    legend.key.size = unit(1, "cm"), # Sets overall area/size of the legend
    legend.text = element_text(size = 14, face = "bold"), # Text size
    title = element_text(size = 14, face = "bold"))

CairoPNG(file=sprintf("D:/Clarissa/HU-GSK591-extended/Combo_vs_HU_pathways.png"),
         units="in",
         width=12.5,
         height=15,
         pointsize=12,
         dpi=300)
print(gg1)
dev.off()
```
